#!/usr/bin/env bash
alias token="oathtool --totp -b $(cat ~/.aws/secretkey)"
source ~/.bash_aliases
select enviroment in "development_dev" "development_staging" "development_demo" "development_ops_staging" "production"
do
  $enviroment
  break
done
