apiVersion: v1
kind: Service
metadata:
  name: cortijo
spec:
  type: NodePort
  selector:
    app: cortijo-app
  ports:
    - port: 30001
      nodePort: 30001
      targetPort: nodejs-port
      protocol: TCP
