apiVersion: v1
kind: ReplicationController
metadata:
  name: cortijo
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: cortijo-app
    spec:
      containers:
      - name: cortijo
        image: enriqueramosmunoz/express_node
        ports:
        - name: nodejs-port
          containerPort: 3000
